#!/usr/bin/env python3
"""Validate the CadQuery/OpenCascade banana clip export workflow."""
from __future__ import annotations

import sys
from pathlib import Path

import banana_clip_cq as model
import config_cq as CQ

SCRIPT_DIR = CQ.ROOT / "scripts"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import config as C
import banana_clip_design_final as G

try:
    import trimesh
except ModuleNotFoundError:  # pragma: no cover
    trimesh = None


RESULT_LINES: list[str] = []


def check(condition: bool, message: str, failures: list[str]) -> None:
    line = ("PASS " if condition else "FAIL ") + message
    print(line)
    RESULT_LINES.append(line)
    if not condition:
        failures.append(line)


def validate_files(failures: list[str]) -> None:
    for name in CQ.ALL_PARTS:
        step = CQ.OUTPUTS_STEP / f"{name}.step"
        stl = CQ.OUTPUTS_CAD_STL / f"{name}.stl"
        check(step.exists(), f"{step.relative_to(CQ.ROOT)} exists", failures)
        check(stl.exists(), f"{stl.relative_to(CQ.ROOT)} exists", failures)
        if step.exists():
            check(step.stat().st_size > 1024, f"{step.name} non-empty STEP size={step.stat().st_size}", failures)
        if stl.exists():
            check(stl.stat().st_size > 1024, f"{stl.name} non-empty STL size={stl.stat().st_size}", failures)
            if trimesh is not None:
                mesh = trimesh.load(stl, force="mesh")
                check(mesh.is_watertight, f"{stl.name} watertight CAD-derived STL", failures)


def validate_pin_clearance(failures: list[str]) -> None:
    hole_radius = G.PIN_HOLE_RADIUS
    check(abs((hole_radius - C.PIN_RADIUS_MM) - C.PIN_CLEARANCE_MM) < 1e-9, f"nominal pin clearance matches config: {C.PIN_CLEARANCE_MM:.3f} mm", failures)
    for name, radius in C.PIN_VARIANTS_MM.items():
        clearance = hole_radius - radius
        check(clearance >= 0.35, f"{name} radial clearance {clearance:.3f} mm", failures)


def validate_tooth_slots(failures: list[str]) -> None:
    upper_body = G.slotted_body_polygon(+1)
    lower_body = G.slotted_body_polygon(-1)
    c1 = upper_body.intersection(G.teeth_union(-1)).area
    c2 = lower_body.intersection(G.teeth_union(+1)).area
    full = G.non_hinge_profile(+1).intersection(G.non_hinge_profile(-1)).area
    check(c1 < 1e-4, f"upper slots clear lower teeth collision area {c1:.6f} mm^2", failures)
    check(c2 < 1e-4, f"lower slots clear upper teeth collision area {c2:.6f} mm^2", failures)
    check(full < 1e-4, f"full non-hinge opposing-arm overlap {full:.6f} mm^2", failures)


def validate_hinge_knuckles(failures: list[str]) -> None:
    upper_boss_ranges = []
    lower_boss_ranges = []
    for side, ranges in [(+1, upper_boss_ranges), (-1, lower_boss_ranges)]:
        base = G.non_hinge_profile(side)
        boss = G.hinge_boss_polygon(side)
        for z0, z1, poly in G.arm_layer_profiles(side):
            boss_only_area = poly.difference(base).intersection(boss).area
            check(poly.is_valid and not poly.is_empty and poly.area > 1.0, f"{'upper' if side > 0 else 'lower'} layer {z0:.2f}-{z1:.2f} valid area={poly.area:.2f}", failures)
            if boss_only_area > 1.0:
                ranges.append((z0, z1))
    for uz0, uz1 in upper_boss_ranges:
        for lz0, lz1 in lower_boss_ranges:
            overlap = min(uz1, lz1) - max(uz0, lz0)
            check(overlap <= 1e-6, f"hinge knuckle Z ranges interleaved upper {uz0:.2f}-{uz1:.2f} vs lower {lz0:.2f}-{lz1:.2f}", failures)
    check(bool(upper_boss_ranges), f"upper hinge knuckle ranges present: {upper_boss_ranges}", failures)
    check(bool(lower_boss_ranges), f"lower hinge knuckle ranges present: {lower_boss_ranges}", failures)


def write_report(failures: list[str]) -> None:
    CQ.DOCS.mkdir(exist_ok=True)
    lines = [
        "# CadQuery Validation Report",
        "",
        "This report is generated by `python cadquery/validate_cq.py`.",
        "",
        "## Result",
        "",
        "FAILED" if failures else "PASSED",
        "",
        "## Checks",
        "",
    ]
    lines.extend(f"- `{line}`" for line in RESULT_LINES)
    if failures:
        lines.extend(["", "## Failures", ""])
        lines.extend(f"- `{line}`" for line in failures)
    (CQ.DOCS / "CADQUERY_VALIDATION_REPORT.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    failures: list[str] = []
    model.generate(CQ.OUTPUTS_STEP, CQ.OUTPUTS_CAD_STL)
    validate_files(failures)
    validate_pin_clearance(failures)
    validate_tooth_slots(failures)
    validate_hinge_knuckles(failures)
    write_report(failures)
    if failures:
        sys.exit(1)


if __name__ == "__main__":
    main()
